import { expect, test, type Page } from "@playwright/test";
async function login(page: Page, email = "admin@agropark.demo") { await page.goto("/login"); await page.getByLabel("E-mail").fill(email); await page.getByLabel("Пароль").fill("password"); await page.getByRole("button", { name: "Открыть dashboard" }).click(); await expect(page).toHaveURL(/\/dashboard/); }
const roles = [{ email: "admin@agropark.demo", badge: "Директор" }, { email: "manager@agropark.demo", badge: "Менеджер" }, { email: "staff@agropark.demo", badge: "Администратор" }, { email: "visitor@agropark.demo", badge: "Гость" }];
test.describe("Public AgroPark app", () => {
  test("home page presents the upgraded client website and keeps pitch in the footer", async ({ page }) => { await page.goto("/"); await expect(page).toHaveTitle(/Некрасово поле/); await expect(page.getByRole("heading", { name: /АгроПарк Некрасово поле/ })).toBeVisible(); await expect(page.getByRole("link", { name: /Забронировать отдых/ }).first()).toBeVisible(); await expect(page.locator("header").getByRole("link", { name: /Презентация/ })).toHaveCount(0); await expect(page.locator("footer").getByRole("link", { name: /Презентация/ })).toBeVisible(); });
  test("pitch deck is a separate Russian presentation", async ({ page }) => { await page.goto("/proposal.html"); await expect(page.getByRole("heading", { name: /Передовая цифровая платформа/ })).toBeVisible(); await expect(page.getByText("Премиальная презентация | июнь 2026", { exact: true })).toBeVisible(); await expect(page.getByText(/Операционная система АгроПарка/)).toBeVisible(); await expect(page.getByRole("link", { name: /Открыть приложение/ }).first()).toBeVisible(); });
  test("chat opens and uses AgroPark fallback", async ({ page }) => { await page.goto("/"); await page.getByRole("button", { name: /AI-чат/ }).click(); await expect(page.getByText("AgroPark AI Assist", { exact: true })).toBeVisible(); await page.getByLabel("Сообщение для AI").fill("Какие цены на гриль-купол?"); await page.keyboard.press("Enter"); await expect(page.getByText(/Гриль-купола начинаются/)).toBeVisible({ timeout: 10_000 }); });
});
test.describe("Authentication and dashboard", () => { for (const role of roles) test(`login as ${role.badge}`, async ({ page }) => { await login(page, role.email); await expect(page.getByTestId("user-role-badge")).toContainText(role.badge); await expect(page.getByRole("heading", { name: "AgroPark OS Dashboard" })).toBeVisible(); }); });


