import { chromium } from "playwright";
const baseURL = process.env.BASE_URL || "http://127.0.0.1:3000";
const browser = await chromium.launch();
const page = await browser.newPage();
await page.goto(baseURL);
await page.getByRole("heading", { name: /АгроПарк Некрасово поле/ }).waitFor({ timeout: 10_000 });
await page.locator("footer").getByRole("link", { name: /Презентация/ }).waitFor({ timeout: 10_000 });
await page.goto(`${baseURL}/proposal.html`);
await page.getByRole("heading", { name: /Передовая цифровая платформа/ }).waitFor({ timeout: 10_000 });
await page.goto(`${baseURL}/login`);
await page.fill('input[name="email"]', "admin@agropark.demo");
await page.fill('input[name="password"]', "password");
await page.getByRole("button", { name: "Открыть dashboard" }).click();
await page.getByRole("heading", { name: "AgroPark OS Dashboard" }).waitFor({ timeout: 10_000 });
await page.goto(baseURL);
await page.getByRole("button", { name: /AI-чат/ }).click();
await page.getByText("AgroPark AI Assist", { exact: true }).waitFor({ timeout: 10_000 });
await page.getByLabel("Сообщение для AI").fill("Какие цены на гриль-купол?");
await page.keyboard.press("Enter");
await page.getByText(/2 300 ₽|3 450 ₽/).waitFor({ timeout: 10_000 });
await browser.close();
